// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StockManagement.Infrastructure.Persistence;

#nullable disable

namespace StockManagement.Infrastructure.Migrations
{
    [DbContext(typeof(StockDbContext))]
    [Migration("20260713132720_AddStockReleaseTypes")]
    partial class AddStockReleaseTypes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("StockManagement.Domain.Entities.Article", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ArticleType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Unit")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.ToTable("Articles");

                    b.HasDiscriminator<string>("ArticleType").HasValue("Article");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("StockManagement.Domain.Entities.StockMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.ToTable("StockMovements");
                });

            modelBuilder.Entity("StockManagement.Domain.Entities.FoodArticle", b =>
                {
                    b.HasBaseType("StockManagement.Domain.Entities.Article");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("SaleType")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("Food");
                });

            modelBuilder.Entity("StockManagement.Domain.Entities.NonFoodArticle", b =>
                {
                    b.HasBaseType("StockManagement.Domain.Entities.Article");

                    b.Property<int>("PackagingLevel")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("NonFood");
                });

            modelBuilder.Entity("StockManagement.Domain.Entities.Article", b =>
                {
                    b.OwnsOne("StockManagement.Domain.ValueObjects.Price", "Price", b1 =>
                        {
                            b1.Property<Guid>("ArticleId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("ExcludingTax")
                                .HasColumnType("TEXT")
                                .HasColumnName("PriceExcludingTax");

                            b1.Property<decimal>("VatRate")
                                .HasColumnType("TEXT")
                                .HasColumnName("VatRate");

                            b1.HasKey("ArticleId");

                            b1.ToTable("Articles");

                            b1.WithOwner()
                                .HasForeignKey("ArticleId");
                        });

                    b.Navigation("Price")
                        .IsRequired();
                });

            modelBuilder.Entity("StockManagement.Domain.Entities.StockMovement", b =>
                {
                    b.HasOne("StockManagement.Domain.Entities.Article", null)
                        .WithMany("Movements")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StockManagement.Domain.Entities.Article", b =>
                {
                    b.Navigation("Movements");
                });
#pragma warning restore 612, 618
        }
    }
}
